release: "Release-1.0"
skipIfAlreadyInstalled: true
artifacts:
  ESObjects: develop
  ESBaseStylesLWC: develop
  ESBaseCodeLWC: develop
  ESSpaceMgmtLWC: develop@
#Added a package dependency to demonstrate how dependencies get installed
packageDependencies:
  sfpowerscripts_artifact: 04t1P000000ka0fQAA 
changelog:
  repoUrl: "https://github.com/dxatscale/easy-spaces-lwc.git"
  workItemFilter: "BRO-[0-9]{3,4}"
