# Validate changes introduced through PR

trigger: none

pr:
    autoCancel: false
    drafts: false
    branches:
        include:
            - develop
pool:
    vmImage: 'ubuntu-latest'

container: dxatscale/sfpowerscripts:latest

variables:
    group: DEVHUB

steps:

    - checkout: self
      persistCredentials: true

    - script: |
        whoami
        export DEBUG=*
        sfdx plugins
        ls -a $XDG_DATA_HOME
      displayName: 'Test'

    - task: DownloadSecureFile@1
      name: devhubKey
      inputs:
          secureFile: 'DEVHUB_SERVER_KEY'

    - script: |
       export DEBUG=*
       sudo sfdx sfpowerscripts:orchestrator:validate -f $(devhubKey.secureFilePath) -i $(DEVHUB_CLIENT_ID) -p CI2 -u $(DEVHUB_USERNAME)  -x
      displayName: 'Validate Changes'
