# Prepare a pool of scratch orgs

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight prepare pool
  branches:
    include:
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          echo 'y' | sfdx plugins:install sfpowerkit
          echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts@alpha
  displayName: 'Install SFDX and Plugins'

- script: |
          echo "$(SALESFORCE_JWT_SECRET_KEY)" > ./JWT_KEYFILE
          sfdx force:auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
  displayName: 'Authenticate DevHub'


- script: |
           sfdx sfpowerscripts:orchestrator:prepare -t CI1 -v devhub --installall --installassourcepackages -m 2
  displayName: 'Prepare a pool of scratch orgs'
