name: Build and Release

trigger:
    - develop

stages:
    - stage: QuickBuild
      displayName: QuickBuild
      dependsOn: []
      jobs:
          - job: QuickBuildJob
            displayName: 'Quick Build the packages'
            variables:
                group: DEVHUB
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest
            steps:
                - checkout: self
                - task: DownloadSecureFile@1
                  name: devhubKey
                  inputs:
                      secureFile: 'DEVHUB_SERVER_KEY'

                - script: |
                      sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
                  displayName: 'Authenticate DevHub'

                - task: CmdLine@2
                  displayName: 'Build All Packages'
                  inputs:
                      script: 'sfdx sfpowerscripts:orchestrator:quickbuild -v devhub'

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: 'artifacts'
                      ArtifactName: 'quickbuild-artifacts'
                      publishLocation: 'Container'

    - stage: Deploy
      displayName: 'Deploy and Validate the packages'
      dependsOn: QuickBuild
      jobs:
          - job: DeployJob
            displayName: 'Deploy the packages'
            variables:
                group: DEVHUB
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest
            steps:
                - checkout: self

                - task: DownloadBuildArtifacts@0
                  inputs:
                      artifactName: 'quickbuild-artifacts'
                      downloadPath: artifacts

                - task: DownloadSecureFile@1
                  name: devhubKey
                  inputs:
                      secureFile: 'DEVHUB_SERVER_KEY'

                - script: |
                      sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
                  displayName: 'Authenticate DevHub'

                - task: CmdLine@2
                  displayName: 'Create ScratchOrg'
                  inputs:
                      script: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 -v devhub'

                - task: CmdLine@2
                  displayName: 'Deploy packages to scratch org'
                  inputs:
                      script: 'sfdx sfpowerscripts:orchestrator:deploy -u scratch-org'

                - task: CmdLine@2
                  displayName: 'Delete scratch org'
                  condition: always()
                  inputs:
                      script: 'sfdx force:org:delete -p -u scratch-org'

    - stage: Build
      displayName: 'Build Production Ready Packages'
      dependsOn: Deploy
      jobs:
          - job: BuildJob
            displayName: 'Build the packages'
            variables:
                group: DEVHUB
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest
            steps:
                - checkout: self
                - task: DownloadSecureFile@1
                  name: devhubKey
                  inputs:
                      secureFile: 'DEVHUB_SERVER_KEY'

                - script: |
                      sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
                  displayName: 'Authenticate DevHub'

                - task: CmdLine@2
                  displayName: 'Build All Packages'
                  inputs:
                      script: 'sfdx sfpowerscripts:orchestrator:build -v devhub'

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: 'artifacts'
                      ArtifactName: 'validated-artifacts'
                      publishLocation: 'Container'

    - stage: Promote
      displayName: 'Promote Packages'
      dependsOn: Build
      jobs:
          - job: PromoteJob
            displayName: 'Promote the packages'
            variables:
                group: DEVHUB
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest
            steps:
                - checkout: self
                - task: DownloadSecureFile@1
                  name: devhubKey
                  inputs:
                      secureFile: 'DEVHUB_SERVER_KEY'

                - task: DownloadBuildArtifacts@0
                  inputs:
                      artifactName: 'validated-artifacts'
                      downloadPath: 'artifacts'

                - script: |
                      sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
                  displayName: 'Authenticate DevHub'

                - task: CmdLine@2
                  displayName: 'Build All Packages'
                  inputs:
                      script: 'sfdx sfpowerscripts:orchestrator:promote -v devhub'
