# Validate changes introduced through PR

trigger: none

pr:
  autoCancel: false
  drafts: false
  branches:
    include:
    - develop
pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DEVHUB

steps:

- task: DownloadSecureFile@1
  name: devhubKey
  inputs:
    secureFile: 'DEVHUB_SERVER_KEY'

- script: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          echo 'y' | sfdx plugins:install sfpowerkit
          echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts@alpha
  displayName: 'Install SFDX and Plugins'

- script: |
          sfdx sfpowerscripts:orchestrator:validate -f $(devhubKey.secureFilePath) -i $(DEVHUB_CLIENT_ID) -p CI2 -u $(DEVHUB_USERNAME)  -x
  displayName: 'Validate Changes'



