# Unique name for this workflow
name: sfpowerscripts prepare

# Definition when the workflow should run
on:
    workflow_dispatch:
    schedule:
     - cron: "0 0 * * *"


# Jobs to be executed
jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                ref: develop

            # Install Salesforce CLI
            - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install

             # Install sfpowerkit
            - name: Install sfpowerkit
              run: |
                  echo 'y' | sfdx plugins:install sfpowerkit

             # Install sfpowerscripts
            - name: Install sfpowerscripts
              run: |
                  echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts@alpha


            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                     echo ${{ secrets.MA_SERVER_KEY }} > ./JWT_KEYFILE
                     sfdx force:auth:jwt:grant -u ${{ secrets.MA_USERNAME }} -i ${{ secrets.MA_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
                     rm -f ./JWT_KEYFILE


            # Prepare a pool of scratch orgs
            - name: 'Prepare a pool of scratch orgs'
              run: 'sfdx sfpowerscripts:orchestrator:prepare -t CI1 -v devhub --installall --installassourcepackages -m 2'
