# Unique name for this workflow
name: sfpowerscripts build and deploy

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - develop

# Jobs to be executed
jobs:
    quickbuild:
        name: QuickBuild the packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
                  sfdx auth:jwt:grant -u ${{ secrets.DEVHUB_USERNAME }} -i ${{ secrets.DEVHUB_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
                  rm -f ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

            # Create all packages
            # In practice, --branch flag should be passed the environment variable for the source branch
            - name: 'Create packages'
              id: sfpowerscripts-build
              run: |
                  pwd
                  sfdx sfpowerscripts:orchestrator:quickbuild -v devhub --diffcheck --branch develop_github

            # Publish artifacts
            - uses: actions/upload-artifact@v2
              with:
                  name: quickbuild-artifacts
                  path: artifacts

    # Simulating a deploy to System Test Environment using a scratch org
    deploy:
        name: Deploy and Validate the packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        needs: quickbuild
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

    #Github Actions are event based and are triggered independently,  There is no currently an option to control concurrency settings
    #on pipelines and in this model, build should be run sequentially
            - name: Wait till previous pipeline has finished this stage
              uses: softprops/turnstyle@v0.1.5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                abort-after-seconds: 1800

              # Download Artifacts
            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: quickbuild-artifacts
                  path: artifacts

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
                  sfdx auth:jwt:grant -u ${{ secrets.DEVHUB_USERNAME }} -i ${{ secrets.DEVHUB_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

            # Create scratch org
            - name: Create scratch org
              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 -v devhub

            # Install all new packages into scratch org
            - name: 'Install new package versions into scratch org'
              run: 'sfdx sfpowerscripts:orchestrator:deploy -u scratch-org'

            # Housekeeping
            - name: Delete scratch org
              if: always()
              run: sfdx force:org:delete -p -u scratch-org

    build:
        name: Build Production Ready packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        needs: deploy
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

              # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
                  sfdx auth:jwt:grant -u ${{ secrets.DEVHUB_USERNAME }} -i ${{ secrets.DEVHUB_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
                  rm -f ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

#Github Actions are event based and are triggered independently,  There is no currently an option to control concurrency settings
#on pipelines and in this model, build should be run sequentially
            - name: Wait till previous pipeline has finished this stage
              uses: softprops/turnstyle@v0.1.5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                abort-after-seconds: 1800

              # Create all packages
              # In practice, --branch flag should be passed the environment variable for the source branch
            - name: 'Create packages'
              id: sfpowerscripts-build
              run: 'sfdx sfpowerscripts:orchestrator:build -v devhub --diffcheck --branch develop_github'

              # Publish artifacts
            - uses: actions/upload-artifact@v2
              with:
                  name: validated-artifacts
                  path: artifacts

    publish:
        name: Publish artifacts to GitHub Packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        needs: build
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: validated-artifacts
                  path: artifacts

            - name: Set NPM registry
              run: |
                  npm set registry https://npm.pkg.github.com

            - name: Authenticate to NPM registry
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${AUTH_TOKEN}" >> ~/.npmrc
              env:
                  AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish
              run: |
                  sfdx sfpowerscripts:orchestrator:publish -d artifacts --npm --scope dxatscale --gittag --pushgittag
