# Unique name for this workflow
name: sfpowerscripts test

# Definition when the workflow should run
on: workflow_dispatch

# Jobs to be executed
jobs:
    promote:
        name: test
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        steps:
            - name: Authenticate to NPM registry
              run: |
                  git remote -v
              env:
                  AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
